# Generated by Django 4.0.3 on 2022-04-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='player.player', verbose_name='Players'),
        ),
    ]
