# Generated by Django 4.0.3 on 2022-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_league_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nickname'),
        ),
    ]
