# Generated by Django 4.0.4 on 2022-04-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manages', to='player.player', verbose_name='Manager'),
        ),
    ]
