# Generated by Django 4.0.4 on 2022-04-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_league_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_manager_for_league', to='player.player', verbose_name='Manager'),
        ),
    ]
