# Generated by Django 4.0.4 on 2022-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_league_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='manager',
        ),
        migrations.AddField(
            model_name='league',
            name='managers',
            field=models.ManyToManyField(related_name='managed_leagues', to='player.player', verbose_name='Manager'),
        ),
    ]
