# Generated by Django 4.0.3 on 2022-04-08 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.PositiveSmallIntegerField(default=1, verbose_name='Ordinal')),
            ],
            options={
                'verbose_name': 'Leg',
                'verbose_name_plural': 'Legs',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw1', models.PositiveSmallIntegerField(default=0, verbose_name='Throw 1')),
                ('throw2', models.PositiveSmallIntegerField(default=0, verbose_name='Throw 2')),
                ('throw3', models.PositiveSmallIntegerField(default=0, verbose_name='Throw 3')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='match.leg', verbose_name='Leg')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='player.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Turn',
                'verbose_name_plural': 'Turns',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typus', models.CharField(choices=[('301', '301'), ('501', '501'), ('701', '701')], default='501', max_length=3, verbose_name='Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date of match')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.league', verbose_name='League')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='player.player', verbose_name='Player 1')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='player.player', verbose_name='Player 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='player.player', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='leg',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='match.match', verbose_name='match'),
        ),
        migrations.AddField(
            model_name='leg',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leg_wins', to='player.player', verbose_name='Winner'),
        ),
    ]
