# Generated by Django 4.0.3 on 2022-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='best_of',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='best of'),
        ),
    ]
