# Generated by Django 4.0.4 on 2022-04-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_leg_options_match_score_player1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ['ord'], 'verbose_name': 'Turn', 'verbose_name_plural': 'Turns'},
        ),
        migrations.AddField(
            model_name='turn',
            name='ord',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ordinal'),
        ),
    ]
