# Generated by Django 4.0.4 on 2022-04-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_turn_options_turn_ord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='ord',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='leg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='match.leg', verbose_name='Leg'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='ord',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='No.'),
        ),
    ]
