# Generated by Django 4.0.4 on 2022-04-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_leg_ord_alter_turn_leg_alter_turn_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='out',
            field=models.CharField(choices=[('SO', 'Single Out'), ('DO', 'Double Out')], default='DO', max_length=2, verbose_name='Out'),
        ),
    ]
