# Generated by Django 4.0.4 on 2022-05-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_league_options_alter_player_options_and_more'),
        ('match', '0006_match_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['timestamp'], 'verbose_name': 'Spiel', 'verbose_name_plural': 'Spiele'},
        ),
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ['ord'], 'verbose_name': 'Runde', 'verbose_name_plural': 'Runden'},
        ),
        migrations.AlterField(
            model_name='leg',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='match.match', verbose_name='Spiel'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='ord',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nr.'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leg_wins', to='player.player', verbose_name='Gewinner'),
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.league', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='player.player', verbose_name='Spieler 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='player.player', verbose_name='Spieler 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_player1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Punkte Spieler 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_player2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Punkte Spieler 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum des Spiels'),
        ),
        migrations.AlterField(
            model_name='match',
            name='typus',
            field=models.CharField(choices=[('301', '301'), ('501', '501'), ('701', '701')], default='501', max_length=3, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='player.player', verbose_name='Gewinner'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='ord',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nr.'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='player.player', verbose_name='Spieler'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='throw1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Wurf 1'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='throw2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Wurf 2'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='throw3',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Wurf 3'),
        ),
    ]
