# Generated by Django 4.0.4 on 2022-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_alter_match_options_alter_turn_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='best_of',
        ),
        migrations.AddField(
            model_name='match',
            name='first_to',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='first to'),
        ),
    ]
