name: Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Check format
        run: find . -type f -name "*.py" | xargs pylint
    
